import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        strawberry: {
          50: '#FFF8F8',
          100: '#FFE4E1',
          200: '#FFCDD2',
          300: '#EF9A9A',
          400: '#E57373',
          500: '#DC143C',
          600: '#C62828',
          700: '#B71C1C',
          800: '#8D1414',
          900: '#5D0E0E',
        },
        cream: {
          50: '#FEFEFE',
          100: '#F5F5DC',
          200: '#F0F0E6',
          300: '#E8E8D4',
          400: '#E0E0C2',
          500: '#D8D8B0',
        },
        rose: {
          50: '#FFF8F8',
          100: '#FFE4E1',
          200: '#FFCCD5',
          300: '#FFB3BA',
          400: '#FF99A3',
          500: '#FF8A95',
        },
        tokyo: {
          50: '#fef7f7',
          100: '#fdeaea',
          200: '#fbd9db',
          300: '#f7b8bc',
          400: '#f18f96',
          500: '#e85d75',
          600: '#d63c5e',
          700: '#b22d4a',
          800: '#962843',
          900: '#81263f',
        },
        osaka: {
          50: '#fffbf0',
          100: '#fff4d9',
          200: '#ffe8b3',
          300: '#ffd882',
          400: '#ffc250',
          500: '#ffab2e',
          600: '#ff8f08',
          700: '#e6730a',
          800: '#bf5c0e',
          900: '#9c4b10',
        },
        nagoya: {
          50: '#faf7ff',
          100: '#f1ecff',
          200: '#e5ddff',
          300: '#d2c1ff',
          400: '#b897ff',
          500: '#9b69ff',
          600: '#8844ff',
          700: '#7932e8',
          800: '#6626c4',
          900: '#5522a3',
        },
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
        noto: ['Noto Sans JP', 'sans-serif'],
        dancing: ['Dancing Script', 'cursive'],
        serif: ['Noto Serif JP', 'serif'],
        rounded: ['M PLUS Rounded 1c', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-tokyo': 'linear-gradient(135deg, #fdeaea 0%, #f7b8bc 50%, #e85d75 100%)',
        'gradient-osaka': 'linear-gradient(135deg, #fff4d9 0%, #ffe8b3 50%, #ffab2e 100%)',
        'gradient-nagoya': 'linear-gradient(135deg, #f1ecff 0%, #e5ddff 50%, #9b69ff 100%)',
        'polka-dot': 'radial-gradient(circle, #FFE4E1 2px, transparent 2px)',
        'hero-gradient': 'linear-gradient(135deg, #FFF8F8 0%, #FFE4E1 100%)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        twinkle: 'twinkle 0.4s ease-in-out',
        float: 'float 3s ease-in-out infinite',
        'pulse-soft': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-soft': 'bounce 1s infinite',
        spinScale: 'spinScale 1.2s ease-out forwards',
        fadeIn: 'fadeIn 1s ease-out forwards',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        twinkle: {
          '0%, 100%': { transform: 'scale(1)' },
          '30%': { transform: 'scale(1.07) rotate(-1deg)' },
          '50%': { transform: 'scale(1.05) rotate(1deg)' },
          '70%': { transform: 'scale(1.06) rotate(-0.5deg)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        spinScale: {
          '0%': { transform: 'scale(0.8) rotate(0deg)', opacity: '0' },
          '50%': { transform: 'scale(1.2) rotate(180deg)', opacity: '1' },
          '100%': { transform: 'scale(1) rotate(360deg)', opacity: '0' },
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
