// Defines the available pages for navigation
export type Page =
  | 'dashboard'
  | 'all-cast'
  | 'store-cast'
  | 'stores'
  | 'advertising'
  | 'ai-copywriter'
  | 'ai-generate-intro'
  | 'intro-list'
  | 'advertising-list'
  | 'hotels'
  | 'hotel-masters'
  | 'interview-reservations'
  | 'recruit-management'
  | 'page-request';

// Represents a cast member
export interface Cast {
  id: string;
  name: string;
  storeIds: string[];
  storePriorities: Record<string, number>; // Added to track rank per store
  status: '在籍中' | '離籍';
  storeStatuses: string[];
  tags: string[];
  photoUrl: string;
  managerComment: string;
  catchphrase: string;
  stats: {
    designations: number;
    repeatRate: number;
    breakdown: {
      new: number;
      repeat: number;
      free: number;
    };
    monthlyPerformance: TimeSeriesData[];
  };
}

// Represents a store
export interface Store {
  id: string;
  name: string;
  slug: string;
  catchphrase: string;
  overview: string;
  address: string;
  phone: string;
  photoUrl: string;
  receptionHours?: string;
  businessHours?: string;
  lineUrl?: string;
  lineId?: string;
  notificationEmail?: string;
}

// Represents a data point for time series charts
// FIX: Made value optional and added an index signature to support chart data with multiple values (e.g., designations, free).
export interface TimeSeriesData {
  name: string;
  value?: number;
  [key: string]: any;
}

// Represents a collection of time series data for different periods
export interface ChartData {
  daily?: TimeSeriesData[];
  weekly?: TimeSeriesData[];
  monthly?: TimeSeriesData[];
  yearly?: TimeSeriesData[];
}

// Represents a single block of content in an intro page
export interface ContentBlock {
  id: string; // Unique ID for the block, e.g., using Date.now() or uuid
  type: 'title' | 'heading' | 'paragraph' | 'image' | 'cast';
  content: string; // Text for paragraph/heading, or base64 data URL for image
  castId?: string; // Only for 'cast' type
}

// Represents the structure of content generated by AI
export interface GeneratedIntroContent {
  contentBlocks: ContentBlock[];
}

// Represents a posted and saved introduction page
export interface GeneratedIntroPage {
  id: string;
  storeId: string;
  castIds: string[];
  createdAt: string; // ISO string date
  contentBlocks: ContentBlock[];
}

// Represents a posted and saved advertisement
export interface AdvertisementPost {
  id: string;
  storeId: string; // 'all' or a specific store id
  copyText: string;
  imageUrl: string; // base64 encoded image string
  createdAt: string; // ISO string date
}
