import type { Metadata } from "next";
import { Inter } from "next/font/google"; // ← Interに変更
import "./globals.css";
import Header from "@/components/Header";
import Head from "next/head";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${inter.variable} bg-background text-foreground antialiased`}
    >
      <Head>
        <link rel="icon" href="/favicon.png" />
      </Head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
